### ISSUE TITLE
Add support for Laravel Dusk

### ISSUE THREAD

**Issue by elcapo** [hawara-es/docker-laravel#5]
A **selenium** Docker container will be available as described in:

```
selenium:
    image: 'selenium/standalone-chrome'
    volumes:
        - '/dev/shm:/dev/shm'
    networks:
        - sail
```

With the new test container running, we should be able to run `./artisan test`.

Check the [source](https://laravel.com/docs/9.x/sail#laravel-dusk).
